name: DreanTest CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # or 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libnss3 libgconf-2-4

      - name: Set up Chrome
        run: |
          sudo apt-get install -y wget unzip
          wget -q -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
          sudo apt-get install -y google-chrome-stable

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true

      - name: Run tests with Maven
        env:
          DISPLAY: :99
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          mvn test

      - name: Move allure-results to target directory
        run: mvn antrun:run@move-allure-results

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Publish Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Upload Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin